version: "3"
services:
  app:
    container_name: go-app
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/go/src/work
    tty: true
    env_file:
      - ./.go_env
    environment:
      - TZ=Asia/Tokyo
